language: c
before_script:
script:
    - "mkdir build"
    - "cd build"
    - "[ -e ../configure ] || ../bootstrap.sh"
    - "../configure || exit $?"
    - "make distcheck || exit $?"
    - "cd .."
    - "git clone git://github.com/contiki-os/contiki.git"
    - "cd contiki"
    - "git checkout 77736062498156589514e325bf1d695152efac68"
    - "cd .."
    - "cd contiki-src/examples/smcp-plugtest"
    - "make TARGET=minimal-net UIP_CONF_IPV6=1 CONTIKI=../../../contiki || exit $?"
    - "cd ../smcp-simple"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
    - "cd ../smcp-complex"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
