language: c
before_script:
script:
    - "mkdir build"
    - "cd build"
    - "[ -e ../configure ] || ../bootstrap.sh"
    - "../configure || exit $?"
    - "make distcheck || exit $?"
    - "cd .."
    - "git clone git://github.com/contiki-os/contiki.git"
    - "cd contiki"
    - "git checkout e1cac43f65eb9ca19f62890f18875b3af1e63a52"
    - "cd .."
    - "cd contiki-src/examples/smcp-plugtest"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
    - "cd ../smcp-simple"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
    - "cd ../smcp-complex"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
