language: c
before_script:
script:
    - "mkdir build"
    - "cd build"
    - "[ -e ../configure ] || ../bootstrap.sh"
    - "../configure || exit $?"
    - "make distcheck || exit $?"
    - "cd .."
    - "git clone git://github.com/contiki-os/contiki.git"
    - "cd contiki"
    - "git checkout 1d69099"
    - "cd .."
    - "make -C contiki-src/examples/smcp-plugtest TARGET=minimal-net CONTIKI=../../../contiki"
    - "make -C contiki-src/examples/smcp-simple TARGET=minimal-net CONTIKI=../../../contiki"
    - "make -C contiki-src/examples/smcp-complex TARGET=native CONTIKI=../../../contiki"
