language: c
before_script:
    - "if [ $BUILD_PLATFORM = contiki ] ; then git clone git://github.com/contiki-os/contiki.git && cd contiki && git checkout 1d69099 && cd .. ; else true ; fi"
    - "if [ $BUILD_PLATFORM = unix ] ; then mkdir build && cd build && ( [ -e ../configure ] || ../bootstrap.sh ) && ../configure && cd .. ; else true ; fi"
script:
    - "make -C $BUILD_MAKEPATH $BUILD_MAKEARGS"
env:
    - BUILD_PLATFORM='unix' BUILD_MAKEPATH='build' BUILD_MAKEARGS='distcheck'
    - BUILD_PLATFORM='contiki' BUILD_MAKEPATH='contiki-src/examples/smcp-plugtest' BUILD_MAKEARGS='TARGET=minimal-net CONTIKI=../../../contiki'
    - BUILD_PLATFORM='contiki' BUILD_MAKEPATH='contiki-src/examples/smcp-simple' BUILD_MAKEARGS='TARGET=minimal-net CONTIKI=../../../contiki'
    - BUILD_PLATFORM='contiki' BUILD_MAKEPATH='contiki-src/examples/smcp-complex' BUILD_MAKEARGS='TARGET=native CONTIKI=../../../contiki'
