language: c
before_script:
script:
    - "mkdir build"
    - "cd build"
    - "[ -e ../configure ] || ../bootstrap.sh"
    - "../configure || exit $?"
    - "make distcheck || exit $?"
    - "cd .."
    - "git clone git://github.com/contiki-os/contiki.git"
    - "cd contiki"
    - "git checkout 0a88373add7b5364dafcb18b21f4063aadfbc6fa"
    - "cd .."
    - "cd contiki-src/examples/smcp-plugtest"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
    - "cd ../smcp-simple"
    - "make TARGET=minimal-net CONTIKI=../../../contiki || exit $?"
